# Bài tập thực hành Nhập môn máy học
# Họ tên: Nguyễn Phú Thành - MSSV: 18110014

In [1]:
from sklearn.datasets import load_diabetes
import numpy as np

In [2]:
diabetes_X, diabetes_y = load_diabetes(return_X_y = True)
X_train, y_train = diabetes_X[:-2], diabetes_y[:-2].reshape(1, -1).T
X_test, y_test = diabetes_X[-2:], diabetes_y[-2:].reshape(1, -1).T

In [3]:
X_train = np.hstack(
    (
        np.ones((X_train.shape[0], 1)),
        X_train
    )
)

In [4]:
X_test = np.hstack(
    (
        np.ones((X_test.shape[0], 1)),
        X_test
    )
)

In [5]:
class SimpleLinearRegression:
    @classmethod
    def MSE_loss(cls, theta, X, y):
        n = y.shape[0]
        loss = 1/(2* n)*(X.dot(theta) - y).T.dot(X.dot(theta) - y)
        return loss.item()
    
    def __init__(self):
        self.theta = None
    
    def fit(self, X, y):
        self.theta = np.linalg.pinv(X.T.dot(X)).dot(X.T).dot(y)
        n = y.shape[0]
        loss = 1/(2 * n) * (X.dot(self.theta) - y).T.dot(X.dot(self.theta) - y)
        return loss.item()
    
    def predict(self, X):
        if self.theta is None:
            raise ValueError('SimpleLinearRegression instance is not fit to the data yet')
        return X.dot(self.theta)

## 1. Hãy dùng bộ dữ liệu dibetes để thiết lập mô hình Linear Regresion

In [6]:
mdl = SimpleLinearRegression()

In [7]:
mse_loss = mdl.fit(X_train, y_train)
print(mse_loss)

1436.2528004632552


In [8]:
mdl.theta

array([[ 152.10620412],
       [  -9.38654069],
       [-239.50541995],
       [ 519.71747928],
       [ 324.62241148],
       [-788.75647584],
       [ 474.10341796],
       [  98.46801188],
       [ 175.8004285 ],
       [ 749.38200399],
       [  67.88567794]])

## 2. Hãy tìm target values của diabetes_X_test rồi so sánh với target values trong diabetes_y_test

In [9]:
y_predict = mdl.predict(X_test)

In [10]:
y_predict

array([[211.74929866],
       [ 53.19292183]])

In [11]:
y_test

array([[220.],
       [ 57.]])

In [12]:
SimpleLinearRegression.MSE_loss(mdl.theta, X_test, y_test)

20.641979211471934

##  3. Tìm hiểu sklearn và làm lại yêu cầu câu 2 (câu cộng điểm)

In [13]:
from sklearn.linear_model import LinearRegression

In [14]:
clf = LinearRegression(fit_intercept = False, normalize = False).fit(X_train, y_train)

In [15]:
clf.coef_

array([[ 152.10620412,   -9.38654069, -239.50541995,  519.71747928,
         324.62241148, -788.75647584,  474.10341796,   98.46801188,
         175.8004285 ,  749.38200399,   67.88567794]])

In [16]:
y_predict = clf.predict(X_test)

In [17]:
y_predict

array([[211.74929866],
       [ 53.19292183]])

In [18]:
y_test

array([[220.],
       [ 57.]])

In [19]:
mse_loss = 1/(2*2) * np.sum((y_predict - y_test)**2)
print(mse_loss)

20.64197921145337
